Fix assets compilation issue
While building Docker, I got an error:

```
Compilation failed:
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
```

The following update turned out to be the solution to this problem:

```
$ npx browserslist@latest --update-db
Latest version:     1.0.30001465
Installed version:  1.0.30001242
...
caniuse-lite has been successfully updated
```