Add a step to download packages information
CI returned the following error:

> E: Unable to fetch some archives, maybe run apt-get update
> or try with --fix-missing?
> Error: Process completed with exit code 100.

As recommended, I added apt-get update to CI.